version: "{build}"

os: Windows Server 2012 R2
platform: x64

environment:
  ruby_version: 22-x64
  matrix:
    - ATOM_CHANNEL: stable
    - ATOM_CHANNEL: beta

install:
  - appveyor DownloadFile https://atom.io/download/windows -FileName AtomSetup.exe
  - AtomSetup.exe /silent
  - cd %APPVEYOR_BUILD_FOLDER%
  - SET PATH=%LOCALAPPDATA%\atom\bin;%PATH%
  - apm clean
  - apm install
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem update --system
  - gem install scss_lint --no-document

before_test:
  - apm --version
  - atom --version
  - ruby --version
  - gem --version
  - scss-lint --version
test_script:
  - atom test

branches:
  only:
    - master

notifications:
  - provider: Email
    on_build_success: false

build: off
deploy: off
